/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsPostRequest
 */
export interface AccountsPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountsPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the AccountsPostRequest interface.
 */
export function instanceOfAccountsPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AccountsPostRequestFromJSON(json: any): AccountsPostRequest {
    return AccountsPostRequestFromJSONTyped(json, false);
}

export function AccountsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function AccountsPostRequestToJSON(value?: AccountsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

