/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiCommandPostRequest
 */
export interface AiCommandPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AiCommandPostRequest
     */
    content: string;
}

/**
 * Check if a given object implements the AiCommandPostRequest interface.
 */
export function instanceOfAiCommandPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "content" in value;

    return isInstance;
}

export function AiCommandPostRequestFromJSON(json: any): AiCommandPostRequest {
    return AiCommandPostRequestFromJSONTyped(json, false);
}

export function AiCommandPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiCommandPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function AiCommandPostRequestToJSON(value?: AiCommandPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}

