/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiVoicePostRequest
 */
export interface AiVoicePostRequest {
    /**
     * 
     * @type {string}
     * @memberof AiVoicePostRequest
     */
    voice: string;
}

/**
 * Check if a given object implements the AiVoicePostRequest interface.
 */
export function instanceOfAiVoicePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "voice" in value;

    return isInstance;
}

export function AiVoicePostRequestFromJSON(json: any): AiVoicePostRequest {
    return AiVoicePostRequestFromJSONTyped(json, false);
}

export function AiVoicePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiVoicePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'voice': json['voice'],
    };
}

export function AiVoicePostRequestToJSON(value?: AiVoicePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'voice': value.voice,
    };
}

