/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiVoiceRequest
 */
export interface AiVoiceRequest {
    /**
     * 
     * @type {string}
     * @memberof AiVoiceRequest
     */
    voice: string;
}

/**
 * Check if a given object implements the AiVoiceRequest interface.
 */
export function instanceOfAiVoiceRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "voice" in value;

    return isInstance;
}

export function AiVoiceRequestFromJSON(json: any): AiVoiceRequest {
    return AiVoiceRequestFromJSONTyped(json, false);
}

export function AiVoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiVoiceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'voice': json['voice'],
    };
}

export function AiVoiceRequestToJSON(value?: AiVoiceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'voice': value.voice,
    };
}

