/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateTimeFilter
 */
export interface DateTimeFilter {
    /**
     * 
     * @type {string}
     * @memberof DateTimeFilter
     */
    lt?: string;
    /**
     * 
     * @type {string}
     * @memberof DateTimeFilter
     */
    lte?: string;
    /**
     * 
     * @type {string}
     * @memberof DateTimeFilter
     */
    gt?: string;
    /**
     * 
     * @type {string}
     * @memberof DateTimeFilter
     */
    gte?: string;
}

/**
 * Check if a given object implements the DateTimeFilter interface.
 */
export function instanceOfDateTimeFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DateTimeFilterFromJSON(json: any): DateTimeFilter {
    return DateTimeFilterFromJSONTyped(json, false);
}

export function DateTimeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateTimeFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lt': !exists(json, 'lt') ? undefined : json['lt'],
        'lte': !exists(json, 'lte') ? undefined : json['lte'],
        'gt': !exists(json, 'gt') ? undefined : json['gt'],
        'gte': !exists(json, 'gte') ? undefined : json['gte'],
    };
}

export function DateTimeFilterToJSON(value?: DateTimeFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lt': value.lt,
        'lte': value.lte,
        'gt': value.gt,
        'gte': value.gte,
    };
}

