/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupTransactions401Response
 */
export interface GroupTransactions401Response {
    /**
     * 
     * @type {string}
     * @memberof GroupTransactions401Response
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof GroupTransactions401Response
     */
    statusCode: number;
}

/**
 * Check if a given object implements the GroupTransactions401Response interface.
 */
export function instanceOfGroupTransactions401Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "statusCode" in value;

    return isInstance;
}

export function GroupTransactions401ResponseFromJSON(json: any): GroupTransactions401Response {
    return GroupTransactions401ResponseFromJSONTyped(json, false);
}

export function GroupTransactions401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupTransactions401Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'statusCode': json['statusCode'],
    };
}

export function GroupTransactions401ResponseToJSON(value?: GroupTransactions401Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'statusCode': value.statusCode,
    };
}

