/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionFilter } from './TransactionFilter';
import {
    TransactionFilterFromJSON,
    TransactionFilterFromJSONTyped,
    TransactionFilterToJSON,
} from './TransactionFilter';

/**
 * 
 * @export
 * @interface GroupTransactionsRequest
 */
export interface GroupTransactionsRequest {
    /**
     * 
     * @type {TransactionFilter}
     * @memberof GroupTransactionsRequest
     */
    filters: TransactionFilter;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupTransactionsRequest
     */
    groupBy: Array<string>;
}

/**
 * Check if a given object implements the GroupTransactionsRequest interface.
 */
export function instanceOfGroupTransactionsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filters" in value;
    isInstance = isInstance && "groupBy" in value;

    return isInstance;
}

export function GroupTransactionsRequestFromJSON(json: any): GroupTransactionsRequest {
    return GroupTransactionsRequestFromJSONTyped(json, false);
}

export function GroupTransactionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupTransactionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filters': TransactionFilterFromJSON(json['filters']),
        'groupBy': json['groupBy'],
    };
}

export function GroupTransactionsRequestToJSON(value?: GroupTransactionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filters': TransactionFilterToJSON(value.filters),
        'groupBy': value.groupBy,
    };
}

