/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionFilter } from './TransactionFilter';
import {
    TransactionFilterFromJSON,
    TransactionFilterFromJSONTyped,
    TransactionFilterToJSON,
} from './TransactionFilter';

/**
 * 
 * @export
 * @interface PaginateTransactionsRequest
 */
export interface PaginateTransactionsRequest {
    /**
     * 
     * @type {TransactionFilter}
     * @memberof PaginateTransactionsRequest
     */
    filters: TransactionFilter;
}

/**
 * Check if a given object implements the PaginateTransactionsRequest interface.
 */
export function instanceOfPaginateTransactionsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filters" in value;

    return isInstance;
}

export function PaginateTransactionsRequestFromJSON(json: any): PaginateTransactionsRequest {
    return PaginateTransactionsRequestFromJSONTyped(json, false);
}

export function PaginateTransactionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginateTransactionsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filters': TransactionFilterFromJSON(json['filters']),
    };
}

export function PaginateTransactionsRequestToJSON(value?: PaginateTransactionsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filters': TransactionFilterToJSON(value.filters),
    };
}

