/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionFilter } from './TransactionFilter';
import {
    TransactionFilterFromJSON,
    TransactionFilterFromJSONTyped,
    TransactionFilterToJSON,
} from './TransactionFilter';

/**
 * 
 * @export
 * @interface TransactionsPagePostRequest
 */
export interface TransactionsPagePostRequest {
    /**
     * 
     * @type {TransactionFilter}
     * @memberof TransactionsPagePostRequest
     */
    filter: TransactionFilter;
}

/**
 * Check if a given object implements the TransactionsPagePostRequest interface.
 */
export function instanceOfTransactionsPagePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filter" in value;

    return isInstance;
}

export function TransactionsPagePostRequestFromJSON(json: any): TransactionsPagePostRequest {
    return TransactionsPagePostRequestFromJSONTyped(json, false);
}

export function TransactionsPagePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsPagePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filter': TransactionFilterFromJSON(json['filter']),
    };
}

export function TransactionsPagePostRequestToJSON(value?: TransactionsPagePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filter': TransactionFilterToJSON(value.filter),
    };
}

