/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionFilter
 */
export interface TransactionFilter {
    /**
     * 
     * @type {number}
     * @memberof TransactionFilter
     */
    accountId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionFilter
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionFilter
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionFilter
     */
    time?: string;
}

/**
 * Check if a given object implements the TransactionFilter interface.
 */
export function instanceOfTransactionFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TransactionFilterFromJSON(json: any): TransactionFilter {
    return TransactionFilterFromJSONTyped(json, false);
}

export function TransactionFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountId': !exists(json, 'accountId') ? undefined : json['accountId'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'time': !exists(json, 'time') ? undefined : json['time'],
    };
}

export function TransactionFilterToJSON(value?: TransactionFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountId': value.accountId,
        'categoryId': value.categoryId,
        'type': value.type,
        'time': value.time,
    };
}

