/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionFilter } from './TransactionFilter';
import {
    TransactionFilterFromJSON,
    TransactionFilterFromJSONTyped,
    TransactionFilterToJSON,
} from './TransactionFilter';

/**
 * 
 * @export
 * @interface TransactionsGroupByPostRequest
 */
export interface TransactionsGroupByPostRequest {
    /**
     * 
     * @type {TransactionFilter}
     * @memberof TransactionsGroupByPostRequest
     */
    filter: TransactionFilter;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionsGroupByPostRequest
     */
    groupBy: Array<string>;
}

/**
 * Check if a given object implements the TransactionsGroupByPostRequest interface.
 */
export function instanceOfTransactionsGroupByPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filter" in value;
    isInstance = isInstance && "groupBy" in value;

    return isInstance;
}

export function TransactionsGroupByPostRequestFromJSON(json: any): TransactionsGroupByPostRequest {
    return TransactionsGroupByPostRequestFromJSONTyped(json, false);
}

export function TransactionsGroupByPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsGroupByPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filter': TransactionFilterFromJSON(json['filter']),
        'groupBy': json['groupBy'],
    };
}

export function TransactionsGroupByPostRequestToJSON(value?: TransactionsGroupByPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filter': TransactionFilterToJSON(value.filter),
        'groupBy': value.groupBy,
    };
}

