/* tslint:disable */
/* eslint-disable */
/**
 * AI Accounting
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionGroupResult
 */
export interface TransactionGroupResult {
    /**
     * 
     * @type {number}
     * @memberof TransactionGroupResult
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGroupResult
     */
    accountId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionGroupResult
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionGroupResult
     */
    type?: string;
}

/**
 * Check if a given object implements the TransactionGroupResult interface.
 */
export function instanceOfTransactionGroupResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function TransactionGroupResultFromJSON(json: any): TransactionGroupResult {
    return TransactionGroupResultFromJSONTyped(json, false);
}

export function TransactionGroupResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionGroupResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'accountId': !exists(json, 'accountId') ? undefined : json['accountId'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function TransactionGroupResultToJSON(value?: TransactionGroupResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'accountId': value.accountId,
        'categoryId': value.categoryId,
        'type': value.type,
    };
}

